sudo: false
language: ruby
rvm:
  - 2.2.0
before_install: gem install bundler -v 1.16.1
notifications:
  slack:
    rooms:
      - seatsio:AGaZISx4HlvoEx6WTbVaX50V
    on_pull_requests: false
    on_failure: always
    on_success: change
